### ISSUE TITLE
[orx-midi] MidiTransceiver throws NoSuchMethodError in JVM shutdown hook

### ISSUE THREAD

**Issue by megadix** [openrndr/orx#181] opened 2021-03-26 13:52 UTC
**Describe the bug**

When a `MidiTransceiver` object is created, orx-midi registers a shutdown hook in the JVM, but it is not called, see #180 
To actually make it call the shutdown hook you need to explicitly call `exitProcess(status)`, but the hook throws a `NoSuchMethodError`.

Example stacktrace:

```
Exception in thread "Thread-1" java.lang.NoSuchMethodError: 'void org.openrndr.extra.midi.MidiTransceiver$2.destroy()'
	at org.openrndr.extra.midi.MidiTransceiver$2.run(MidiTransceiver.kt:114)
```

**To Reproduce**

1. create a simple program
2. initialize a MidiTransceiver (see "MIDI" tutorial)
3. register some listeners, e.g. controlChanged, noteOn, etc.
4. add a "program ended listener", e.g. `ended.listen { exitProcess(0) }`
5. run the program
6. close the main window

**Expected behavior**

When closing the main window the program should exit normally.

**Context:**

- OS and version: Windows 10
 - OpenRNDR version: ~~0.3.15~~ `0.3.46`
 - Java Version: tested with OpenJDK 11 and 14

**Comment by megadix** [comment] 2021-03-29 15:22
Sorry, version number is  `0.3.46`, not `0.3.15`

I've corrected it in the original description.

Sorry for the error

**Comment by edwinRNDR** [comment] 2021-04-10 13:36
Apologies for being so slow on this. Will try to reproduce this, but the `NoSuchMethodError` make it look like incompatible versions of OPENRNDR and ORX are mixed.

**Comment by edwinRNDR** [comment] 2021-04-10 14:38
I have the same issue here on a Windows 10 machine

**Comment by edwinRNDR** [comment] 2021-04-10 14:50
It looks like the class loader already unloaded the class when calling `destroy` in the shutdown hook. This is new to me :)

**Comment by edwinRNDR** [comment] 2021-04-10 15:23
Fixed in https://github.com/openrndr/orx/commit/ddc81fc521ca5898a80a216624b646e9aa31b9a8 , we will likely do a new release in the coming days that will include it.

**Closed by edwinRNDR** 2021-04-10 15:23 UTC
Labels: bug
